# Generated by Django 3.2 on 2022-04-05 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my8gag', '0002_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
